using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;
using UnityEngine.SceneManagement;

namespace _Project.UI.Flow.Runtime
{
    /// <summary>
    /// A runtime representation of a UI Flow graph.
    /// This ScriptableObject is generated by the <see cref="_Project.UI.Flow.Editor.UIFlowImporter"/>.
    /// </summary>
    public class UIFlowRuntimeGraph : ScriptableObject
    {
        /// <summary>
        /// The list of nodes in the graph.
        /// </summary>
        [SerializeReference]
        public List<UIFlowRuntimeNode> nodes = new List<UIFlowRuntimeNode>();

        /// <summary>
        /// The index of the start node in the <see cref="nodes"/> list.
        /// </summary>
        public int startNodeIndex = -1;

        /// <summary>
        /// Gets a node by its index.
        /// </summary>
        /// <param name="index">The index of the node.</param>
        /// <returns>The node if the index is valid; otherwise, null.</returns>
        public UIFlowRuntimeNode GetNode(int index)
        {
            if (index >= 0 && index < nodes.Count) return nodes[index];
            return null;
        }
    }

    /// <summary>
    /// Base class for all runtime nodes in a UI Flow graph.
    /// </summary>
    [Serializable]
    public abstract class UIFlowRuntimeNode
    {
        /// <summary>
        /// The name of the node.
        /// </summary>
        public string nodeName;

        /// <summary>
        /// The list of outgoing links from this node.
        /// </summary>
        public List<UIFlowLink> links = new List<UIFlowLink>();
    }

    /// <summary>
    /// Represents a link between two nodes in a UI Flow graph.
    /// </summary>
    [Serializable]
    public class UIFlowLink
    {
        /// <summary>
        /// The name of the port this link originates from.
        /// </summary>
        public string portName;

        /// <summary>
        /// The index of the target node in the graph's nodes list.
        /// </summary>
        public int targetNodeIndex;
    }

    /// <summary>
    /// A runtime node that marks the starting point of a UI Flow.
    /// </summary>
    [Serializable]
    public class StartRuntimeNode : UIFlowRuntimeNode { }

    /// <summary>
    /// A runtime node that displays a UI view using a <see cref="VisualTreeAsset"/>.
    /// </summary>
    [Serializable]
    public class ViewRuntimeNode : UIFlowRuntimeNode
    {
        /// <summary>
        /// The UI Toolkit asset to display.
        /// </summary>
        public VisualTreeAsset viewAsset;

        /// <summary>
        /// Optional delay before showing the view.
        /// </summary>
        public float showDelay;

        /// <summary>
        /// If true, the flow automatically transitions to the next node.
        /// </summary>
        public bool autoNext;

        /// <summary>
        /// The delay in seconds before auto-transitioning.
        /// </summary>
        public float waitSeconds;

        /// <summary>
        /// If true, the navigation history is cleared when this node is executed.
        /// </summary>
        public bool clearHistory;

        /// <summary>
        /// If true, the UI view is hidden when transitioning to the next node.
        /// </summary>
        public bool hideOnNext;

        /// <summary>
        /// Mapping of button names to ports.
        /// </summary>
        public List<string> buttonNames = new List<string>();
    }

    /// <summary>
    /// Defines the type of action in a sequence item.
    /// </summary>
    [Serializable]
    public enum UISequenceItemType
    {
        /// <summary>
        /// Replaces the current UI content.
        /// </summary>
        ShowUI,

        /// <summary>
        /// Adds UI content to the current root.
        /// </summary>
        AddUI,

        /// <summary>
        /// Waits for a specified duration.
        /// </summary>
        Wait
    }

    /// <summary>
    /// Represents an individual item within a <see cref="UISequenceRuntimeNode"/>.
    /// </summary>
    [Serializable]
    public class UISequenceRuntimeItem
    {
        /// <summary>
        /// The type of action to perform.
        /// </summary>
        public UISequenceItemType type;

        /// <summary>
        /// The UI asset involved (if applicable).
        /// </summary>
        public VisualTreeAsset viewAsset;

        /// <summary>
        /// The duration to wait (if type is Wait).
        /// </summary>
        public float waitSeconds;
    }

    /// <summary>
    /// A runtime node that executes a linear sequence of UI operations.
    /// </summary>
    [Serializable]
    public class UISequenceRuntimeNode : UIFlowRuntimeNode
    {
        /// <summary>
        /// The items in the sequence.
        /// </summary>
        public List<UISequenceRuntimeItem> items = new List<UISequenceRuntimeItem>();

        /// <summary>
        /// Button names that can trigger transitions from this sequence.
        /// </summary>
        public List<string> buttonNames = new List<string>();

        /// <summary>
        /// If true, automatically transitions to the "Next" port upon completion.
        /// </summary>
        public bool nextOnComplete;
    }

    /// <summary>
    /// A runtime node that triggers a scene load operation.
    /// </summary>
    [Serializable]
    public class LoadSceneRuntimeNode : UIFlowRuntimeNode
    {
        /// <summary>
        /// The name of the scene to load.
        /// </summary>
        public string sceneName;

        /// <summary>
        /// If true, avoids reloading if the target scene is already active.
        /// </summary>
        public bool preventLoadingSameScene = true;

        /// <summary>
        /// Specifies whether to load the scene additively or as a single scene.
        /// </summary>
        public LoadSceneMode loadSceneMode = LoadSceneMode.Single;

        /// <summary>
        /// Allows controlling when the scene becomes active after loading.
        /// </summary>
        public bool allowSceneActivation = true;

        /// <summary>
        /// Minimum delay before activation (if <see cref="allowSceneActivation"/> is managed).
        /// </summary>
        public float sceneActivationDelay = 0.2f;

        /// <summary>
        /// If true, the node waits for the scene to finish loading before continuing.
        /// </summary>
        public bool waitForSceneToLoad = true;
    }

    /// <summary>
    /// A runtime node that terminates the application.
    /// </summary>
    [Serializable]
    public class QuitRuntimeNode : UIFlowRuntimeNode { }
}